apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ixhdb48qb-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ixhdb48qb-nodejs 
  name: ixhdb48qb-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ixhdb48qb-nodejs 
